services:
  - type: web
    name: file-processor-server
    runtime: node
    repo: https://github.com/YAMRAJ275/61573940335470
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0